version: '3.8'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgres://user:password@database:5432/mydb
      PORT: 8080
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:8082"
    depends_on:
      - backend

volumes:
  pgdata:
